# TensorFlow Parte II - Tensores

In [2]:
import tensorflow as tf
import numpy as np

2023-09-06 22:31:45.233168: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-06 22:31:53.469007: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


Tensores en TensorFlow son arreglos multidimensionales con un tipo uniforme (`dtype`). Una [lista de dtypes](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType).

Tensores en TensorFlow son tipos **inmutables** (no se puede cambiar sus valores después de su creación). Si queremos cambiar valores usamos `Variable` (en el próximo Notebook).

## Tensores básicos



Un escalar es un tensor de rango 0.

In [2]:
rango_0_tensor = tf.constant(4)
print(rango_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


2023-09-06 14:05:39.199261: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-09-06 14:05:39.509328: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


Un vector es un tensor de rango 1:

In [3]:
rango_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rango_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


Una matriz es un tensor de rango 2.

In [5]:
rango_2_tensor = tf.constant([[1, 2], 
                              [3, 4], 
                              [5, 6]], dtype=tf.float16) #Float 16 bits!
print(rango_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


Pueden ver que el tipo de datos del tensor arriba es de $16$ bits, menos que un `float` normal ($32$ bits). Este es porque la precisión numérica no es tan importante, normalemente, en machine learning.

También podemos crear tensores con más ejes, por ejemplo $3$:

In [6]:
rango_3_tensor = tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9]],
    [[10,11,12,13,14],
     [15,16,17,18,19]],
    [[20,21,22,23,24],
     [25,26,27,28,29]],
])

In [7]:
print(rango_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


| NumPy | Front | Block |
| ----- | ----- | ----- |
|![](3-axis_numpy.png)|![](3-axis_front.png)|![](3-axis_block.png)|

In [8]:
np.array(rango_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [9]:
rango_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

Tensores pueden incluir `float`, `int`, `complex`, `string`...

Operaciones matemáticas con tensores:

In [10]:
a = tf.constant([[1, 2],
                 [3, 4]])

b = tf.constant([[1, 1],
                 [1, 1]])

In [11]:
print(tf.add(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [13]:
print(tf.multiply(a, b))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [14]:
print(tf.matmul(a, b))

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [15]:
print(a + b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [16]:
print(a * b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [17]:
print(a @ b)

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [18]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

In [19]:
print(tf.reduce_max(c))

tf.Tensor(10.0, shape=(), dtype=float32)


In [20]:
print(tf.math.argmax(c))

tf.Tensor([1 0], shape=(2,), dtype=int64)


Función de [softmax](https://en.wikipedia.org/wiki/Softmax_function):

In [21]:
print(tf.nn.softmax(c))

tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


Cuando TensorFlow espera un tensor, típicamente funciona con cualquier objeto que se puede convertir a un tensor con `tf.convert_to_tensor`:

In [23]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [24]:
tf.reduce_max([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [25]:
tf.reduce_max(np.array([1,2,3]))

<tf.Tensor: shape=(), dtype=int64, numpy=3>

* **Shape** (forma): número de elementos en cada eje
* **Rank** (rango): número de ejes
* **Axis** o **Dimension**: una dimensión partícular de un tensor
* **Size**: tamaño, número total de elementos

Tensores y objetos de la clase `tf.TensorShape` tienen propiedades convenientes para obtener esta información:

In [26]:
rango_4_tensor = tf.zeros([3, 2, 4, 5])

| Shape | Block |
| ----- | ----- |
|![](shape.png)|![](4-axis_block.png)|

In [28]:
print("Tipo de cada elemento:", rango_4_tensor.dtype)

Tipo de cada elemento: <dtype: 'float32'>


In [29]:
print("Número de ejes:", rango_4_tensor.ndim)

Número de ejes: 4


In [30]:
print("Forma del tensor:", rango_4_tensor.shape)

Forma del tensor: (3, 2, 4, 5)


In [32]:
print("No. de elementos en eje 0:", rango_4_tensor.shape[0])

No. de elementos en eje 0: 3


In [33]:
print("No. de elementos en último eje:", rango_4_tensor.shape[-1])

No. de elementos en último eje: 5


In [35]:
print("No. total de elementos (3*2*4*5):", tf.size(rango_4_tensor).numpy())

No. total de elementos (3*2*4*5): 120


Los atributos `Tensor.ndim` y `Tensor.shape` no son tensores. Si necesitamos un `Tensor` usamos `tf.rank` y `tf.shape`.

In [37]:
rango_4_tensor.ndim

4

In [38]:
tf.rank(rango_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [40]:
rango_4_tensor.shape

TensorShape([3, 2, 4, 5])

In [39]:
tf.shape(rango_4_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5], dtype=int32)>

El orden de los ejes puede ser importante. En aplicaciones en machine learning el siguiente orden es típico:

![](shape2.png)

Así los *features* están en regiones contiguas de memoria.

## El uso de los índices

Las reglas son como en NumPy:

* índices comienzan en `0`.
* índices negativos cuentan desde el último elemento hacia atrás.
* usamos doble punto `:` para rebanadas (*slices*) `comienzo:último:salto`

In [41]:
rango_1_tensor = tf.constant([0,1,1,2,3,5,8,13,21,34])
print(rango_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


In [42]:
print("Primero:", rango_1_tensor[0].numpy())

Primero: 0


In [43]:
print("Segundo:", rango_1_tensor[1].numpy())

Segundo: 1


In [44]:
print("Último:", rango_1_tensor[-1].numpy())

Último: 34


Índices escalares eliminan el eje, pero rebanadas mantienen el eje:

In [45]:
print("Todo:", rango_1_tensor[:].numpy())

Todo: [ 0  1  1  2  3  5  8 13 21 34]


In [46]:
print("Antes el elemento 4:", rango_1_tensor[:4].numpy())

Antes el elemento 4: [0 1 1 2]


In [47]:
print("Del elemento 4 al final:", rango_1_tensor[4:].numpy())

Del elemento 4 al final: [ 3  5  8 13 21 34]


In [48]:
print("Del elemento 2, antes de 7:", rango_1_tensor[2:7].numpy())

Del elemento 2, antes de 7: [1 2 3 5 8]


In [49]:
print("Cada segundo elemento:", rango_1_tensor[::2].numpy())

Cada segundo elemento: [ 0  1  3  8 21]


In [50]:
print("En orden inversa:", rango_1_tensor[::-1].numpy())

En orden inversa: [34 21 13  8  5  3  2  1  1  0]


### Índices con varios ejes

In [51]:
print(rango_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [52]:
print(rango_2_tensor[1,1].numpy())

4.0


In [53]:
print("Segunda fila:", rango_2_tensor[1, :].numpy())

Segunda fila: [3. 4.]


In [54]:
print("Segunda columna:", rango_2_tensor[:, 1].numpy())

Segunda columna: [2. 4. 6.]


In [55]:
print("Última fila:", rango_2_tensor[-1, :].numpy())

Última fila: [5. 6.]


In [56]:
print("Primer elemento en última columna:", rango_2_tensor[0, -1].numpy())

Primer elemento en última columna: 2.0


In [58]:
print("Saltar la primera fila:\n", rango_2_tensor[1:, :].numpy())

Saltar la primera fila:
 [[3. 4.]
 [5. 6.]]


In [59]:
print(rango_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


Eligiendo el último *feature* en todas ubicaciones en cada instancia en el lote:

| Todos los datos | Valores elegidos |
| --------------- | ---------------- |
|![](index1.png)  |![](index2.png)   |

## Manipulación de la forma

In [60]:
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [61]:
print(x.shape.as_list())

[3, 1]


Se puede modificar la forma de un tensor por el uso de `tf.reshape`. Esta operación es rápida porque los datos no están duplicados.

In [62]:
reformado = tf.reshape(x, [1, 3])

In [64]:
print(x.shape)

(3, 1)


In [65]:
print(reformado.shape)

(1, 3)


Los datos mantienen su organización en la memoria, y se crea un nuevo tensor, con la forma pedida, que apunta a los mismos datos.

TensorFlow ocupa ordenamiento por fila (*row-major order*) como en C.

In [66]:
print(rango_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


Si aplanamos los datos (*flatten*) podemos ver como están organizados en la memoria.

In [68]:
print(tf.reshape(rango_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


Para este tensor de $3 \times 2 \times 5$, reformar a $(3\times2)\times5$ o $3\times(2\times5)$ tiene sentido, ya que las rebanadas no se mezclan.

| Antes | $3 \times (2\times 5)$ | $(3\times 2) \times 5$ |
| ----- | ---------------------- | ---------------------- |
|![](reshape-before.png)|![](reshape-good1.png)|![](reshape-good2.png)|

Reformar funcionará para cualquier forma nueva con el mismo número total de elementos. Pero no será útil sin respetar el orden de los ejes...

No se puede reordenar los ejes con `tf.reshape` (hay que usar `tf.transpose`).

In [70]:
print(tf.reshape(rango_3_tensor, [2,3,5]))

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32)


In [71]:
print(tf.reshape(rango_3_tensor, [5, 6]))

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32)


In [73]:
try:
    tf.reshape(rango_3_tensor, [7, -1])
except Exception as e:
    print(f"{type(e).__name__}: {e}")

InvalidArgumentError: {{function_node __wrapped__Reshape_device_/job:localhost/replica:0/task:0/device:CPU:0}} Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


## Más sobre `DTypes`

Cuando se crea un tensor de un objeto de Python, se puede especificar el tipo de datos.

Si no se lo hace, TensorFlow elige un tipo que puede representar los datos.

In [77]:
tensor_f64 = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
print(tensor_f64)

tf.Tensor([2.2 3.3 4.4], shape=(3,), dtype=float64)


In [78]:
tensor_f16 = tf.cast(tensor_f64, dtype=tf.float16)
print(tensor_f16)

tf.Tensor([2.2 3.3 4.4], shape=(3,), dtype=float16)


In [80]:
tensor_u8 = tf.cast(tensor_f16, dtype=tf.uint8)
print(tensor_u8)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


## Broadcasting

Este es un concepto de NumPy. La idea es "extender" tensores más pequeños para tener tensores del mismo tamaño en operaciones matemáticas.

Un ejemplo simple es en el cálculo del producto de un tensor con un escalar. El escalar está "extendida" para tener las mismas dimensiones que el tensor.

In [81]:
x = tf.constant([1,2,3])

In [82]:
y = tf.constant(2)

In [83]:
z = tf.constant([2,2,2])

In [84]:
print(tf.multiply(x,2))

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [85]:
print(x*y)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [87]:
print(x*z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)


También, ejes con longitud $1$ pueden ser extendidas para coincidir con otros argumentos en la operación.

Por ejemplo, multiplicación de una matriz $3\times1$ elemento-por-elemento con otra matriz $1\times4$ resulta en una matriz $3\times4$.

![](broadcasting.png)

In [88]:
x = tf.reshape(x, [3,1])

In [89]:
y = tf.range(1, 5)

In [90]:
print(x)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


In [91]:
print(y)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [92]:
print(tf.multiply(x, y))

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


En la mayoría de los casos nunca materializamos los tensores extendidos en la memoria, así que la operación es eficiente.

Podemos materializar el tensor que resulta de *broadcasting* con `tf.broadcast_to`:

In [93]:
print(tf.broadcast_to(tf.constant([1,2,3]), [3,3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


Hay más información [aquí](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html) sobre *broadcasting* en NumPy. Puede ser bastante complicado!

## Tensores irregulares

Un tensor con un número variable de elementos en algún eje se llama *ragged* (irregular). Se puede usar `tf.ragged.RaggedTensor` para datos así.

![](ragged.png)

In [3]:
lista_irregular = [
    [0,1,2,3],
    [4,5],
    [6,7,8],
    [9]
]

In [4]:
try:
    tensor = tf.constant(lista_irregular)
except Exception as e:
    print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


2023-09-06 22:35:48.644206: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-09-06 22:35:48.967974: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [5]:
tensor_irregular = tf.ragged.constant(lista_irregular)
print(tensor_irregular)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [6]:
print(tensor_irregular.shape)

(4, None)


## Tensores de *strings*

`tf.string` es un `dtype`, así que podemos representar datos como *strings* (arreglos de bytes de tamaño variable) en tensores.

Los *strings* son "atómicos": no se puede acceder los carácteres individuales como en *strings* normales de Python. La longitud del *string* NO es un eje del tensor.

In [7]:
tensor_string_escalar = tf.constant("Lobo gris")
print(tensor_string_escalar)

tf.Tensor(b'Lobo gris', shape=(), dtype=string)


También podemos tener vectores de *strings*:

In [13]:
tensor_de_strings = tf.constant(["Lobo gris", "Perro blanco grande", "Gato negro"])

In [14]:
print(tensor_de_strings)

tf.Tensor([b'Lobo gris' b'Perro blanco grande' b'Gato negro'], shape=(3,), dtype=string)


La letra `b` indica que son *byte-strings* (no es *unicode*). Pasando carácteres de *unicode* son registrados usando utf-8.

In [15]:
tf.constant("🥳👍")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

Hay algunas funciones disponibles para manipular *strings*:

In [16]:
print(tf.strings.split(tensor_string_escalar, sep=" "))

tf.Tensor([b'Lobo' b'gris'], shape=(2,), dtype=string)


In [17]:
print(tf.strings.split(tensor_de_strings))

<tf.RaggedTensor [[b'Lobo', b'gris'], [b'Perro', b'blanco', b'grande'], [b'Gato', b'negro']]>


In [18]:
texto = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(texto, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


No se puede usar `tf.cast` para convertir un tensor de *strings* en números, pero se puede convertir a bytes y después a números.

In [19]:
byte_strings = tf.strings.bytes_split(tf.constant("Pato"))

In [22]:
byte_ints = tf.io.decode_raw(tf.constant("Pato"), tf.uint8)

In [24]:
print("Byte strings: ", byte_strings)

Byte strings:  tf.Tensor([b'P' b'a' b't' b'o'], shape=(4,), dtype=string)


In [25]:
print("Bytes: ", byte_ints)

Bytes:  tf.Tensor([ 80  97 116 111], shape=(4,), dtype=uint8)


In [26]:
unicode_bytes = tf.constant("アヒル 🦆")

In [27]:
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")

In [28]:
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

In [29]:
print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe3\x82\xa2' b'\xe3\x83\x92' b'\xe3\x83\xab' b' ' b'\xf0\x9f\xa6\x86'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([ 12450  12498  12523     32 129414], shape=(5,), dtype=int32)


## Tensores dispersos (*sparse tensors*)

En TensorFlow existen objetos de tipo `tf.sparse.SparseTensor` y operaciones relacionadas para guardar datos dispersos en una manera eficiente.

![](sparse.png)

In [30]:
tensor_disperso = tf.sparse.SparseTensor(indices=[[0,0], [1,2]],
                                         values=[1, 2],
                                         dense_shape=[3,4])

In [31]:
print(tensor_disperso)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [32]:
print(tf.sparse.to_dense(tensor_disperso))

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
